spring:
  application:
    name: eurekaserver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: shopping
    password: shopping
server:
  port: 8761
eureka:
  instance:
    # changed hosts file in the computer
    hostname: eureka1
  client:
    service-url:
      #     register to another server to achieve high availability
      defaultZone: http://eureka2:8762/eureka/
    registerWithEureka: true
    fetchRegistry: true