#web port
server:
  port: 8082

# Datasource configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: shopping
    password: shopping
# Redis
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 8
        min-idle: 0

    timeout: 0
  session:
    store-type: none
  kafka:
    bootstrap-servers: 192.168.0.103:9092,192.168.0.103:9093,192.168.0.103:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# MyBatis Mapper Config
mybatis:
  mapper-locations: classpath:mappers/*.xml

resilience4j:
  # Resilience4j rate limiter -> RateLimiterProperties
  ratelimiter:
    instances:
      backendB:
        limit-for-period: 10 # allowed requests
        limit-refresh-period: 3s
        timeout-duration: 3s
        register-health-indicator: true # 是否注册到健康监测