server:
  port: 8088

spring:
  application:
    name: orderscan
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: shopping
    password: shopping
  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9093,kafka3:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  session:
    store-type: none

# MyBatis Mapper Config
mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      #     register to another server to achieve high availability
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
