server:
  port: 8089

spring:
  application:
    name: commonutils
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: shopping
    password: shopping
  session:
    store-type: none

# MyBatis Mapper Config
mybatis:
  mapper-locations: classpath:mapper/*.xml
