server:
  port: 8085

spring:
  application:
    name: userservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: shopping
    password: shopping
  session:
    store-type: none
  # Redis
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0

# MyBatis Mapper Config
mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      #     register to another server to achieve high availability
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
    fetch-registry: true